name: "Compile and Publish"

on:
  workflow_dispatch:
  schedule:
    - cron: '43 0 * * *'

permissions: write-all

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: takayama-lily/oicq

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: 'https://npm.pkg.github.com'

    - name: Install global dependencies
      run: sudo apt install moreutils

    - name: Setup Github Packages
      run: |
        jq '.repository |= "https://github.com/Zxilly/oicq-nightly.git"' package.json | sponge package.json
        COMMIT_SHA=$(git rev-parse --short HEAD)
        OLD_VERSION=$(jq -r ".version" package.json)
        NEW_VERSION="${OLD_VERSION}-$COMMIT_SHA"
        jq ".version |= \"$NEW_VERSION\"" package.json | sponge package.json
        jq ".name |= \"@zxilly/oicq\"" package.json | sponge package.json

    - name: Install project dependencies
      run: |
        npm install
        npm install -g typescript

    - name: Build
      run: |
        # workaround for temporary bug in oicq
        set +e
        tsc
        npm pack
        set -e

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: oicq
        path: zxilly-oicq-*.tgz

    - name: Publish to Github Packages
      run: npm publish --access public --registry https://npm.pkg.github.com || true # version may duplicate, just ignore
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish-branch:
    runs-on: ubuntu-latest
    needs: publish-package
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: git-repo

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Get artifact
      uses: actions/download-artifact@v3
      with:
        name: oicq
        path: oicq
    
    - name: Extract artifact
      working-directory: oicq
      run: |
        tar -xzf zxilly-oicq-*.tgz
        rm zxilly-oicq-*.tgz
    
    - name: Cleanup and create
      working-directory: git-repo
      run: |
        if git rev-parse --verify publish > /dev/null 2>&1; then
          git branch -D publish
        fi
        git switch --orphan publish
        cp -r ../oicq/* .
        git add .
        git commit -m "Publish"
        git push -f origin publish

        VERSION_STRING=$(jq -r ".version" package.json)
        VERSION_BRANCH="publish-${VERSION_STRING}"
        # if branch not exist
        if ! git rev-parse --verify $VERSION_BRANCH > /dev/null 2>&1; then
          cp -r ../oicq/* .
          git add .
          git commit -m "Publish $VERSION_STRING"
          git push -f origin $VERSION_BRANCH
        fi



        

        