name: "Compile"

on:
  workflow_dispatch:
  schedule:
    - cron: '43 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: takayama-lily/oicq

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: 'https://npm.pkg.github.com'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        npm install -g typescript
        sudo apt install moreutils jq

    - name: Build
      run: tsc

    - name: Setup Github Packages
      run: |
        jq '.repository |= "https://github.com/Zxilly/oicq-nightly.git"' package.json | sponge package.json

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}