name: "Compile and Publish"

on:
  workflow_dispatch:
  schedule:
    - cron: '43 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: takayama-lily/oicq

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: 'https://npm.pkg.github.com'

    - name: Install global dependencies
      run: sudo apt install moreutils jq

    - name: Setup Github Packages
      run: |
        jq '.repository |= "https://github.com/Zxilly/oicq-nightly.git"' package.json | sponge package.json
        COMMIT_SHA=$(git rev-parse --short HEAD)
        jq ".version |= \"$COMMIT_SHA\"" package.json | sponge package.json

    - name: Install project dependencies
      run: |
        npm install
        npm install -g typescript

    - name: Build
      run: |
        # workaround for temporary bug in oicq
        set +e
        tsc
        set -e

    - name: Publish to Github Packages
      run: npm publish --access public --registry https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}